export const GET_APPROVALS=`GET_APPROVALS`;
export const GET_APPROVALS_WEEK=`GET_APPROVALS_WEEK`;
export const UPDATE_APPROVAL='UPDATE_APPROVAL';
export const UPDATE_ALL_APPROVALS='UPDATE_ALL_APPROVALS';
export const DELETE_APPROVALS=`DELETE_APPROVAL`;
export const SET_USER_INFO=`SET_USER_INFO`;